// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/hours" | "/admin/logs" | "/admin/settings" | "/admin/users" | "/calendar" | "/change-password" | "/login" | "/setup"
type AppRouteHandlerRoutes = "/api/admin/audit-logs" | "/api/admin/settings/atera-key" | "/api/admin/users" | "/api/admin/users/[id]" | "/api/admin/users/[id]/reset-password" | "/api/admin/work-logs" | "/api/auth/change-password" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/calendar/events" | "/api/calendar/events/[id]" | "/api/health/auth" | "/api/setup" | "/api/tickets" | "/api/tickets/[id]" | "/api/tickets/[id]/attachments" | "/api/tickets/[id]/comments" | "/api/tickets/[id]/resolve" | "/pwa-icon-192" | "/pwa-icon-512"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/hours": {}
  "/admin/logs": {}
  "/admin/settings": {}
  "/admin/users": {}
  "/api/admin/audit-logs": {}
  "/api/admin/settings/atera-key": {}
  "/api/admin/users": {}
  "/api/admin/users/[id]": { "id": string; }
  "/api/admin/users/[id]/reset-password": { "id": string; }
  "/api/admin/work-logs": {}
  "/api/auth/change-password": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/calendar/events": {}
  "/api/calendar/events/[id]": { "id": string; }
  "/api/health/auth": {}
  "/api/setup": {}
  "/api/tickets": {}
  "/api/tickets/[id]": { "id": string; }
  "/api/tickets/[id]/attachments": { "id": string; }
  "/api/tickets/[id]/comments": { "id": string; }
  "/api/tickets/[id]/resolve": { "id": string; }
  "/calendar": {}
  "/change-password": {}
  "/login": {}
  "/pwa-icon-192": {}
  "/pwa-icon-512": {}
  "/setup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
